base_url = "https://genetics.wustl.edu/bclab"
compile_sass = true
build_search_index = false
title = "Cohen Lab"
description = "The laboratory of Barak Cohen at Washington University in St. Louis"
ignored_content = ["*.csv", ".DS_Store", "*.py"]
taxonomies = [
    { name = "authors", feed = false, paginate_by = 10 },
    { name = "tags", feed = false, paginate_by = 10 },
]
minify_html = true

[markdown]
highlight_code = false
external_links_target_blank = true
external_links_no_referrer = true

[slugify]
taxonomies = "off"

[extra]
